/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Components: typeof import('./src/components/index.vue')['default']
    EditPasswd: typeof import('./src/components/EditPasswd.vue')['default']
    EditProfile: typeof import('./src/components/EditProfile.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    Loading: typeof import('./src/components/loading/index.vue')['default']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Svg: typeof import('./src/components/svg/index.vue')['default']
    Text: typeof import('./src/components/text.vue')['default']
    User: typeof import('./src/components/User.vue')['default']
    UserFormDialog: typeof import('./src/components/UserFormDialog.vue')['default']
    UserManageBar: typeof import('./src/components/UserManageBar.vue')['default']
    UserTable: typeof import('./src/components/UserTable.vue')['default']
    Websocket: typeof import('./src/components/Websocket.vue')['default']
  }
}
